### ISSUE TITLE
Using official alpine image 

### ISSUE THREAD

**Issue by qrevel** [cgswong/docker-aws#10]
Hello,

Why `gliderlabs/alpine:3.6` is used instead of the [official](https://hub.docker.com/_/alpine/) alpine image?

**Comment by cgswong** [comment]
@qrevel There were some minor differences between the two originally and I wanted to maintain consistency with my other work. I do need to review, since it has been some time, on if that is still the case.

**Comment by cgswong** [comment]
Looks like the differences are no longer relevant so I will be switching to the now recommended official images. Thanks again for your comment!
